name: Test
on:
  push:
    branches: [master, main]

env:
  LAAS_APP_TOKEN: ${{ secrets.LAAS_APP_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i -g yarn
      - run: yarn
      - run: yarn test
      - run: yarn build